[Service]
port_number = 50000
log_file = "log.lnav"
rate_limite = 100

[Format]
priority = true     #int
timestamp = true    #string
hostname = true     #string
application = true  #string
pid = true          #int
msgid = true        #string
message = true      #string